[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"

# Redirect all requests to index.html for SPA (except API and static files)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API functions
[functions]
  directory = "netlify/functions"

# Environment variables that will be available during build
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
