[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,VITE_SUPABASE_ANON_KEY,SUPABASE_URL,VITE_SUPABASE_URL,NODE_ENV"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,.env*,config/**"

# Build caching for better performance
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# API functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for SPA and API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_APP_ENVIRONMENT = "deploy-preview"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_APP_ENVIRONMENT = "branch-deploy"
